project_id = "bbscffnivgfwelxudlzy"

[functions.create-checkout-session]
verify_jwt = true

[functions.create-anonymous-checkout]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false