// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbscffnivgfwelxudlzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJic2NmZm5pdmdmd2VseHVkbHp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMzU3NDMsImV4cCI6MjA3MzYxMTc0M30.sj31Wa1nczbQ7w6n9BZMeKoNPK7YZdMLGe41qsAk7HQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});