name: Hosted EE Build

on:
  workflow_dispatch:
    inputs:
      image:
        description: "Target image (e.g., quay.io/org/ee:tag)"
        required: true
      ee_yaml_path:
        description: "Path to execution-environment.yml (ignored if ee_zip_b64 used)"
        default: "execution-environment.yml"
        required: true
      ee_zip_b64:
        description: "Base64-encoded ZIP of EE files (optional)"
        required: false
      push:
        description: "Push after build"
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Prepare workspace
        run: mkdir -p ee

      - name: Use repo files or reconstruct ZIP
        run: |
          if [ -n "${{ github.event.inputs.ee_zip_b64 }}" ]; then
            echo "${{ github.event.inputs.ee_zip_b64 }}" | base64 -d > ee/ee.zip
            unzip ee/ee.zip -d ee
          else
            echo "No ee_zip_b64 provided; using repo files at ${{ github.event.inputs.ee_yaml_path }}"
          fi

      - name: Checkout repo (for repo-based build)
        uses: actions/checkout@v4
        with:
          path: repo

      - name: Locate EE files
        run: |
          if [ -f ee/execution-environment.yml ]; then
            echo "Using EE files from ZIP"
            ls -la ee
          else
            echo "Using EE files from repo"
            mkdir -p ee
            cp "repo/${{ github.event.inputs.ee_yaml_path }}" ee/execution-environment.yml
            # Copy neighbors if present
            for f in requirements.yml requirements.txt bindep.txt ; do
              [ -f "repo/$f" ] && cp "repo/$f" "ee/$f"
            done
            ls -la ee
          fi

      - name: Install ansible-builder
        run: |
          python3 -m pip install --upgrade pip
          pip install "ansible-builder>=3.1"

      - name: Docker login
        if: ${{ inputs.push == 'true' }}
        env:
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        run: |
          REG="$(echo "${{ inputs.image }}" | awk -F/ '{print $1}')"
          echo "$REGISTRY_PASSWORD" | docker login --username "$REGISTRY_USERNAME" --password-stdin "$REG"

      - name: Build EE
        working-directory: ee
        run: |
          test -f execution-environment.yml || { echo "missing execution-environment.yml"; exit 2; }
          ansible-builder build \
            -t "${{ inputs.image }}" \
            -f execution-environment.yml \
            --container-runtime docker

      - name: Push EE
        if: ${{ inputs.push == 'true' }}
        run: docker push "${{ inputs.image }}"
